<a href="https://colab.research.google.com/github/AdityaFaisal/DecisionTree_DataMining/blob/main/Decision_Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
#Import library numpy, pandas dan sclikit-learn
import numpy as np
import pandas as pd
from sklearn import tree

In [76]:
#Membaca dataset dari file ke pandas dataFrame
irisDataset = pd.read_csv('horses.csv', delimiter=',', header=0)

In [77]:
irisDataset.head()

id  age  sex_id  sire_id  dam_id  prize_money
0  17  2.0     1.0     17.0    17.0      31760.0
1  86  5.0     1.0     55.0    86.0      60235.0
2  82  5.0     3.0     69.0    82.0      56075.0
3  77  6.0     1.0     10.0    77.0     166580.0
4  46  5.0     1.0     41.0    46.0       9800.0

In [23]:
#mengubah kelas (kolom "species") dari string ke unique-integer
irisDataset["prize_money"] = pd.factorize(irisDataset.prize_money)[0]

In [24]:
irisDataset.head()

id  age  sex_id  sire_id  dam_id  prize_money
0  17  2.0     1.0     17.0    17.0            0
1  86  5.0     1.0     55.0    86.0            1
2  82  5.0     3.0     69.0    82.0            2
3  77  6.0     1.0     10.0    77.0            3
4  46  5.0     1.0     41.0    46.0            4

In [25]:
print(irisDataset)

          id  age  sex_id  sire_id   dam_id  prize_money
0         17  2.0     1.0     17.0     17.0            0
1         86  5.0     1.0     55.0     86.0            1
2         82  5.0     3.0     69.0     82.0            2
3         77  6.0     1.0     10.0     77.0            3
4         46  5.0     1.0     41.0     46.0            4
...      ...  ...     ...      ...      ...          ...
14108  13953  3.0     2.0    236.0  11379.0          176
14109  13957  5.0     1.0    397.0  11382.0         7291
14110  13960  5.0     3.0    311.0  11383.0          977
14111  13965  3.0     2.0    249.0  11386.0         1241
14112  13968  4.0     3.0      8.0  11388.0         8357

[14113 rows x 6 columns]


In [26]:
#menghapus kolom "id"
irisDataset = irisDataset.drop(labels="id", axis=1)

In [27]:
print(irisDataset)

       age  sex_id  sire_id   dam_id  prize_money
0      2.0     1.0     17.0     17.0            0
1      5.0     1.0     55.0     86.0            1
2      5.0     3.0     69.0     82.0            2
3      6.0     1.0     10.0     77.0            3
4      5.0     1.0     41.0     46.0            4
...    ...     ...      ...      ...          ...
14108  3.0     2.0    236.0  11379.0          176
14109  5.0     1.0    397.0  11382.0         7291
14110  5.0     3.0    311.0  11383.0          977
14111  3.0     2.0    249.0  11386.0         1241
14112  4.0     3.0      8.0  11388.0         8357

[14113 rows x 5 columns]


In [28]:
#mengubah dataframe ke array numpy
irisDataset = irisDataset.to_numpy()

In [29]:
print(irisDataset)

[[2.0000e+00 1.0000e+00 1.7000e+01 1.7000e+01 0.0000e+00]
 [5.0000e+00 1.0000e+00 5.5000e+01 8.6000e+01 1.0000e+00]
 [5.0000e+00 3.0000e+00 6.9000e+01 8.2000e+01 2.0000e+00]
 ...
 [5.0000e+00 3.0000e+00 3.1100e+02 1.1383e+04 9.7700e+02]
 [3.0000e+00 2.0000e+00 2.4900e+02 1.1386e+04 1.2410e+03]
 [4.0000e+00 3.0000e+00 8.0000e+00 1.1388e+04 8.3570e+03]]


In [39]:
#membagi dataset => 80 baris data untuk training dan 20 baris data untuk testing
dataTraining = np.concatenate((irisDataset[0:20, :], irisDataset[60:100, :]), axis=0)
dataTesting = np.concatenate((irisDataset[20:60, :], irisDataset[100:200, :]), axis=0)                              

In [40]:
print(dataTraining)
len(dataTraining)

[[2.000e+00 1.000e+00 1.700e+01 1.700e+01 0.000e+00]
 [5.000e+00 1.000e+00 5.500e+01 8.600e+01 1.000e+00]
 [5.000e+00 3.000e+00 6.900e+01 8.200e+01 2.000e+00]
 [6.000e+00 1.000e+00 1.000e+01 7.700e+01 3.000e+00]
 [5.000e+00 1.000e+00 4.100e+01 4.600e+01 4.000e+00]
 [4.000e+00 1.000e+00 7.300e+01 8.700e+01 5.000e+00]
 [6.000e+00 1.000e+00 6.200e+01 8.000e+01 6.000e+00]
 [3.000e+00 2.000e+00 5.000e+00 5.000e+00 7.000e+00]
 [5.000e+00 1.000e+00 8.000e+01 9.800e+01 8.000e+00]
 [3.000e+00 1.000e+00 2.700e+01 2.800e+01 9.000e+00]
 [2.000e+00 2.000e+00 2.200e+01 2.200e+01 1.000e+01]
 [4.000e+00 3.000e+00 3.100e+01 3.200e+01 1.100e+01]
 [5.000e+00 3.000e+00 6.000e+00 6.000e+00 1.200e+01]
 [3.000e+00 1.000e+00 4.000e+00 4.000e+00 1.300e+01]
 [5.000e+00 1.000e+00 6.200e+01 7.100e+01 1.400e+01]
 [6.000e+00 3.000e+00 4.600e+01 5.400e+01 1.500e+01]
 [8.000e+00 1.000e+00 6.000e+01 6.900e+01 1.600e+01]
 [3.000e+00 1.000e+00 2.600e+01 2.700e+01 1.700e+01]
 [3.000e+00 1.000e+00 1.600e+01 1.600e+01 1.80

60

In [41]:
print(dataTesting)
len(dataTesting)

[[4.0000e+00 1.0000e+00 2.5000e+01 2.5000e+01 2.0000e+01]
 [4.0000e+00 1.0000e+00 4.7000e+01 5.5000e+01 2.1000e+01]
 [4.0000e+00 3.0000e+00 4.0000e+01 1.0000e+02 2.2000e+01]
 [5.0000e+00 3.0000e+00 5.8000e+01 6.6000e+01 2.3000e+01]
 [5.0000e+00 3.0000e+00 4.2000e+01 4.7000e+01 2.4000e+01]
 [4.0000e+00 3.0000e+00 1.2000e+01 1.2000e+01 2.5000e+01]
 [7.0000e+00 3.0000e+00 3.0000e+01 9.1000e+01 2.6000e+01]
 [9.0000e+00 1.0000e+00 7.9000e+01 9.5000e+01 2.7000e+01]
 [8.0000e+00 1.0000e+00 7.2000e+01 8.5000e+01 2.8000e+01]
 [5.0000e+00 3.0000e+00 9.0000e+00 9.0000e+00 2.9000e+01]
 [7.0000e+00 1.0000e+00 6.3000e+01 7.3000e+01 3.0000e+01]
 [4.0000e+00 1.0000e+00 5.1000e+01 5.9000e+01 3.1000e+01]
 [3.0000e+00 2.0000e+00 1.1000e+01 1.1000e+01 3.2000e+01]
 [3.0000e+00 2.0000e+00 3.5000e+01 3.8000e+01 3.3000e+01]
 [8.0000e+00 1.0000e+00 7.0000e+01 8.3000e+01 3.4000e+01]
 [4.0000e+00 1.0000e+00 1.8000e+01 5.1000e+01 3.5000e+01]
 [6.0000e+00 3.0000e+00 6.1000e+01 7.0000e+01 3.6000e+01]
 [7.0000e+00 1

140

In [69]:
#memecah dataset ke input label
inputTraining = dataTraining[:, 0:1]
inputTesting = dataTesting[:, 0:1]
labelTraining = dataTraining[:, 1]
labelTesting = dataTesting[:, 1]
print(labelTraining)
len(labelTraining)

[1. 1. 3. 1. 1. 1. 1. 2. 1. 1. 2. 3. 3. 1. 1. 3. 1. 1. 1. 1. 1. 1. 3. 3.
 3. 1. 1. 1. 4. 2. 2. 1. 2. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1. 1. 1. 1.
 3. 3. 2. 1. 3. 1. 2. 1. 3. 1. 3. 1.]


60

In [70]:
#mendefinisikan decision tree classifier
model = tree.DecisionTreeClassifier()

In [71]:
#mentraining model
model = model.fit(inputTraining, labelTraining)

In [72]:
#memprediksi input data testing
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)

Label Sebenarnya :  [1. 1. 3. 3. 3. 3. 3. 1. 1. 3. 1. 1. 2. 2. 1. 1. 3. 1. 1. 2. 1. 1. 1. 1.
 1. 1. 6. 1. 2. 1. 3. 3. 3. 1. 3. 3. 1. 1. 3. 1. 1. 1. 1. 1. 1. 3. 3. 1.
 1. 3. 1. 3. 3. 1. 1. 1. 3. 1. 1. 3. 3. 3. 1. 1. 1. 3. 3. 1. 3. 3. 1. 1.
 3. 3. 1. 3. 3. 1. 1. 3. 1. 1. 1. 1. 1. 1. 2. 2. 4. 1. 1. 1. 1. 2. 1. 1.
 1. 1. 2. 2. 1. 1. 1. 3. 3. 1. 3. 3. 2. 2. 2. 3. 1. 1. 3. 1. 3. 1. 1. 1.
 3. 1. 2. 2. 1. 1. 3. 3. 4. 1. 1. 1. 3. 1. 2. 1. 1. 3. 1. 1.]
Hasil Prediksi :  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [73]:
#menghitung akurasi
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar :", prediksiBenar, "data")
print("Prediksi Salah :", prediksiSalah, "data")
print("Akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah) * 100, "%")

Prediksi Benar : 79 data
Prediksi Salah : 61 data
Akurasi : 56.42857142857143 %
